### ISSUE TITLE
Remove jobs buttons

### ISSUE THREAD

**Issue by arnaudbenard** [stonecircle/kue-ui#5]
I refine this into 
- removeByState
- removeByState&Type 

which is very helpful in production environments. 

User can have a empty link under their filtered/sub-menu of state/job_type in current kue-ui which removes all jobs of the current filter/sub-menu.

**Comment by chaudhryjunaid** [comment]
+1, very useful needed feature!

**Comment by chaudhryjunaid** [comment]
any progress?

**Comment by chaudhryjunaid** [comment]
Another useful enhancement can be a small circular cross button next to each job in addition to the big delete button inside job details because job details sometime need scrolling to get to the delete button.

**Comment by kartik-koinex** [comment]
I would love to see a checkbox before each job, so that users can select multiple jobs and delete them all at once. Also remove jobs by their status and type should also be there. Probably a button "delete them all" at the top of the every job list.I can take up this issue, are there any active contributors to this repo?

**Comment by agarwalkartik** [comment]
I would love to see a checkbox before each job, so that users can select multiple jobs and delete them all at once. Also remove jobs by their status and type should also be there. Probably a button "delete them all" at the top of the every job list.I can take up this issue, are there any active contributors to this repo?
